import subprocess
import sys
import os
import builtins as _bi
import contextvars as _cv

# ══════════════════════════════════════════════════════════════════════════════
# THREAD-TAGGED LOGGING: har worker thread (T1, T2, ...) ka naam terminal ke
# har log line ke aage [Tn] lag ke dikhega — pata chalega kaunsi line kis
# thread ki hai. contextvars ki wajah se asyncio task ke andar ke SAARE
# print() (process_account ke andar wale bhi) automatically tag ho jaate hain.
# ══════════════════════════════════════════════════════════════════════════════
_worker_tag = _cv.ContextVar("worker_tag", default="")
_orig_print = _bi.print

def _tagged_print(*args, **kwargs):
    tag = _worker_tag.get()
    if tag and args and isinstance(args[0], str) and ("[%s]" % tag) not in args[0]:
        args = (("[%s] " % tag) + args[0],) + tuple(args[1:])
    _orig_print(*args, **kwargs)

_bi.print = _tagged_print

# ══════════════════════════════════════════════════════════════════════════════
# BOOTSTRAP: Auto-install all required packages BEFORE any imports
# This runs first so even a fresh Google Cloud Shell works out of the box.
# ══════════════════════════════════════════════════════════════════════════════
def _bootstrap_install():
    # ── Step 1: Install Python packages ─────────────────────────────────────
    pkgs = {
        "playwright":         "playwright",
        "playwright_stealth": "playwright-stealth",
        "pyotp":              "pyotp",
        "requests":           "requests",
        "redis":              "redis",
    }
    needs_restart = False
    for import_name, pip_name in pkgs.items():
        try:
            __import__(import_name)
        except ImportError:
            print(f"[BOOTSTRAP] Installing Python package: {pip_name}...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pip_name])
            needs_restart = True

    # ── Step 2: Install Playwright Chromium browser + system deps ────────────
    try:
        subprocess.run(
            [sys.executable, "-m", "playwright", "install", "chromium"],
            capture_output=True, text=True
        )
        subprocess.run(
            [sys.executable, "-m", "playwright", "install-deps", "chromium"],
            capture_output=True
        )
    except Exception as e:
        print(f"[BOOTSTRAP] playwright install warning: {e}")

    # ── Step 3: Install Tor via apt-get if not present ───────────────────────
    if subprocess.run(["which", "tor"], capture_output=True).returncode != 0:
        print("[BOOTSTRAP] Tor not found. Installing via apt-get...")
        subprocess.run(["sudo", "apt-get", "update", "-y"], check=True)
        subprocess.run(["sudo", "apt-get", "install", "-y", "tor"], check=True)
        print("[BOOTSTRAP] Tor installed successfully.")
    else:
        print("[BOOTSTRAP] Tor already installed.")

    # ── Step 4: Configure torrc with IsolateSOCKSAuth ───────────────────────
    torrc_content = (
        "# Auto-generated by insta_tor_ip_gclud.py\n"
        "SocksPort 9050 IsolateSOCKSAuth\n"
        "DataDirectory /var/lib/tor\n"
        "Log notice stdout\n"
    )
    torrc_path = "/etc/tor/torrc"
    try:
        with open(torrc_path, "w") as f:
            f.write(torrc_content)
        print("[BOOTSTRAP] torrc configured with IsolateSOCKSAuth.")
    except PermissionError:
        proc = subprocess.Popen(
            ["sudo", "tee", torrc_path],
            stdin=subprocess.PIPE, stdout=subprocess.DEVNULL
        )
        proc.communicate(torrc_content.encode())
        print("[BOOTSTRAP] torrc configured (via sudo tee).")

    # ── Step 5: (Re)start Tor service ───────────────────────────────────────
    print("[BOOTSTRAP] Starting Tor service...")
    subprocess.run(["sudo", "service", "tor", "stop"], capture_output=True)
    try:
        subprocess.run(["sudo", "service", "tor", "start"], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        # Some cloud envs need systemctl instead of service
        subprocess.run(["sudo", "systemctl", "restart", "tor"], check=True)

    # ── Step 6: Wait for Tor to be ready ────────────────────────────────────
    import time as _time
    print("[BOOTSTRAP] Waiting for Tor to bootstrap on port 9050...")
    for _ in range(30):
        try:
            import socket as _sock
            s = _sock.create_connection(("127.0.0.1", 9050), timeout=2)
            s.close()
            print("[BOOTSTRAP] Tor is ready!")
            break
        except OSError:
            _time.sleep(2)
    else:
        print("[BOOTSTRAP] WARNING: Tor may not have started. Continuing anyway...")

    # ── Step 7: Restart self if packages were newly installed ────────────────
    if needs_restart:
        print("[BOOTSTRAP] Restarting script with all packages available...")
        os.execv(sys.executable, [sys.executable] + sys.argv)

_bootstrap_install()
# ══════════════════════════════════════════════════════════════════════════════

import asyncio
from concurrent.futures import ThreadPoolExecutor
import random
import string
import time
import requests
import re
import pyotp
import tempfile
import shutil
import json
import socket
import struct
from playwright.async_api import Playwright, async_playwright, expect
from playwright_stealth import Stealth


# ==========================================
# GOOGLE CLOUD / LINUX CONFIGURATION
# ==========================================
HEADLESS_MODE = True  # Always headless on Google Cloud
TOR_PORT = 9050        # System Tor (not Tor Browser)
# Playwright's new headless mode supports extensions natively!
EXTENSION_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "free vpn")

class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'



# ── OTP manager (inlined: no separate otp_manager.py needed) ─────────────
_OTP_DOMAIN_CACHE = {"v": None, "ts": 0}

def _otp_api_url(email_addr, digits):
    """OTP API URL — domain Redis `config:otp_domain` se aata hai (panel se live change).
    60s cache, default nearbygirls.us."""
    import time as _t
    c = _OTP_DOMAIN_CACHE
    if c["v"] is None or _t.time() - c["ts"] > 60:
        try:
            v = _r().get("config:otp_domain")
            if v:
                v = v.strip().lower().replace("https://", "").replace("http://", "").split("/")[0]
                if v:
                    c["v"] = v
        except Exception:
            pass
        c["ts"] = _t.time()
        if not c["v"]:
            c["v"] = "nearbygirls.us"
    return "https://%s/api/otp.php?email=%s&digits=%s" % (c["v"], email_addr, digits)

def start_imap_listener():
    # No longer needed, we poll the API directly.
    pass

def prefetch_seen_ids(email_addr, seen_ids):
    """Fetches the current OTP email ID and adds it to seen_ids
    so we don't accidentally process old OTPs."""
    email_addr = email_addr.lower().strip()
    for digits in [8, 6]:
        url = _otp_api_url(email_addr, digits)
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                data = response.json()
                if data.get("success") and data.get("data"):
                    msg_id = data["data"].get("email_id")
                    if msg_id:
                        seen_ids.add(str(msg_id))
        except Exception:
            pass

def fetch_otp(email_addr, seen_ids=None, max_retries=30):
    """Fetches the OTP for a given email address using the custom temp-mail API."""
    email_addr = email_addr.lower().strip()
    if seen_ids is None:
        seen_ids = set()
    for _ in range(max_retries):
        for digits in [8, 6]:
            url = _otp_api_url(email_addr, digits)
            try:
                response = requests.get(url, timeout=10)
                if response.status_code == 200:
                    data = response.json()
                    if data.get("success") and data.get("data"):
                        msg_id = str(data["data"].get("email_id"))
                        otp = data["data"].get("otp")
                        if msg_id and msg_id in seen_ids:
                            continue
                        if otp:
                            seen_ids.add(msg_id)
                            return otp
            except Exception:
                pass
        time.sleep(4)
    return None

def generate_random_name():
    first_names = ["Rahul", "Sonali", "Priya", "Amit", "Neha", "Vikram", "Anjali", "Rohan", "Sneha", "Karan", "Pooja", "Arjun", "Kavya", "Aditya", "Riya"]
    last_names = ["Kumar", "Kumari", "Sharma", "Singh", "Verma", "Gupta", "Das", "Patel", "Reddy", "Mehta", "Jain", "Bose"]
    return f"{random.choice(first_names)} {random.choice(last_names)}"


# ══════════════════════════════════════════════════════════════════════════
# FLEET BRIDGE: Redis queue + results for 100-300 workers (multi-machine OK)
#   Queue:     BRPOPLPUSH queue:pending -> queue:processing:<worker-id> (atomic claim)
#   Results:   LPUSH results   (panel ingests -> SQLite -> Google Sheets, batched)
#   Heartbeat: HSET workers:hb (panel fleet view)
# If Redis is unreachable, results are buffered to worker_results_<id>.jsonl
# and re-sent automatically when Redis is back.
# ══════════════════════════════════════════════════════════════════════════
import argparse as _ap
_ap_p = _ap.ArgumentParser()
_ap_p.add_argument("--worker-id", default="")
# THREADS: yahi number badlo
THREADS = 12
_ap_p.add_argument("--threads", type=int, default=None)  # None = dashboard (Redis fleet:default_threads) se lo
_ap_p.add_argument("--redis-url", default=os.environ.get("REDIS_URL", "redis://:3c0ac0e48103d8c5674c16de3336a305@3.110.210.40:6379/0"))
_APARGS, _ = _ap_p.parse_known_args()
REDIS_URL = _APARGS.redis_url
import getpass
WORKER_ID = _APARGS.worker_id or ("%s-%d" % (getpass.getuser(), os.getpid()))
_redis_client = None

def _r():
    global _redis_client
    if _redis_client is None:
        import redis as _rl
        _redis_client = _rl.from_url(REDIS_URL, socket_timeout=10, decode_responses=True)
    return _redis_client

def _fleet_threads():
    if _APARGS.threads:
        return max(1, min(50, _APARGS.threads))
    try:
        v = _r().get("threads:%s" % WORKER_ID) or _r().get("fleet:default_threads")
        if v:
            return max(1, min(50, int(v)))
    except Exception:
        pass
    return 10

WORKER_THREADS = _fleet_threads()
# ── Auto-renew: fresh Tor + fresh process every N accounts or M hours ─────────
# Lambe run me Tor ke circuits slow hote hain aur exit IPs ki reputation jal
# jaati hai (Instagram throttle karta hai) — isliye beech me khud renew.
# Tune:  env WORKER_RESTART_EVERY=18   |  env WORKER_RESTART_HOURS=4
# Band:  env WORKER_RESTART_EVERY=0  (0 = kabhi auto-restart nahi)
WORKER_RESTART_EVERY = int(os.environ.get("WORKER_RESTART_EVERY", "18"))
WORKER_RESTART_HOURS = float(os.environ.get("WORKER_RESTART_HOURS", "4"))
PROC_KEY = "queue:processing:" + WORKER_ID
CURRENT_EMAIL = ""
RESULT_BACKUP = "worker_results_%s.jsonl" % WORKER_ID

def _push_result_payload(payload):
    _r().lpush("results", json.dumps(payload))

def report_result(status, qid, data):
    payload = {"worker_id": WORKER_ID, "queue_id": qid, "status": status,
               "created_at": time.strftime("%Y-%m-%d %H:%M:%S")}
    payload.update(data)
    # flush local backup first (results saved while Redis was down)
    try:
        if os.path.exists(RESULT_BACKUP):
            with open(RESULT_BACKUP) as f:
                lines = f.readlines()
            remain = []
            for ln in lines:
                try:
                    _push_result_payload(json.loads(ln))
                except Exception:
                    remain.append(ln)
            if remain:
                with open(RESULT_BACKUP, "w") as f:
                    f.writelines(remain)
            else:
                os.remove(RESULT_BACKUP)
    except Exception:
        pass
    try:
        _push_result_payload(payload)
    except Exception:
        with open(RESULT_BACKUP, "a") as f:
            f.write(json.dumps(payload) + "\n")

def claim_one():
    """Exactly ONE account claim karo (atomic BRPOPLPUSH).
    Returns (raw, item) | None (queue empty) | "DOWN" (Redis unreachable)."""
    try:
        r = _r()
        r.ping()
    except Exception:
        return "DOWN"
    try:
        raw = r.brpoplpush("queue:pending", PROC_KEY, timeout=25)
    except Exception:
        return None
    if not raw:
        return None
    try:
        return (raw, json.loads(raw))
    except Exception:
        ack_claim(raw)  # corrupt entry — claim chhodo taaki processing me stuck na rahe
        return None

def ack_claim(raw):
    try:
        _r().lrem(PROC_KEY, 1, raw)
    except Exception:
        pass

def heartbeat_loop():
    import time as _ht
    start = _ht.time()
    while True:
        try:
            _r().hset("workers:hb", WORKER_ID, json.dumps({
                "id": WORKER_ID, "machine": socket.gethostname(),
                "threads": WORKER_THREADS, "current": CURRENT_EMAIL,
                "paused": _is_paused(), "ver": _WORKER_VER,
                "uptime": int(_ht.time() - start)}))
            _r().expire("workers:hb", 120)
        except Exception:
            pass
        _ht.sleep(30)


def _worker_ver():
    try:
        import hashlib as _hv
        return _hv.sha256(open(os.path.abspath(__file__), "rb").read()).hexdigest()[:12]
    except Exception:
        return ""

_WORKER_VER = _worker_ver()
_PAUSED = False


def _is_paused():
    if _PAUSED:
        return True
    try:
        r = _r()
        if r.get("paused:" + WORKER_ID) == "1":
            return True
        if r.get("fleet:paused") == "1":
            return True
    except Exception:
        pass
    return False


def _self_update(url, sha256):
    import hashlib as _hl, os as _os, sys as _sys
    me = _os.path.abspath(__file__)
    if not url or not sha256:
        print(f"{Colors.WARNING}[fleet] update: missing url/sha256{Colors.ENDC}")
        return
    try:
        import urllib.request as _ur
        tmp = me + ".new"
        print(f"{Colors.OKCYAN}[fleet] downloading update...{Colors.ENDC}")
        _ur.urlretrieve(url, tmp)
        h = _hl.sha256(open(tmp, "rb").read()).hexdigest()
        if h != sha256:
            _os.remove(tmp)
            print(f"{Colors.FAIL}[fleet] update REJECTED: sha256 mismatch{Colors.ENDC}")
            return
        _os.replace(tmp, me)
        print(f"{Colors.OKGREEN}[fleet] updated OK, restarting...{Colors.ENDC}")
        _os.execv(_sys.executable, [_sys.executable, me] + _sys.argv[1:])
    except Exception as e:
        print(f"{Colors.FAIL}[fleet] update failed: {e}{Colors.ENDC}")


def _handle_command(cmd):
    global _PAUSED, WORKER_THREADS
    act = (cmd.get("action") or "").lower()
    if act == "pause":
        _PAUSED = True
        try:
            _r().set("paused:" + WORKER_ID, "1")
        except Exception:
            pass
        print(f"{Colors.WARNING}[fleet] paused by panel{Colors.ENDC}")
    elif act == "resume":
        _PAUSED = False
        try:
            _r().delete("paused:" + WORKER_ID)
        except Exception:
            pass
        print(f"{Colors.OKGREEN}[fleet] resumed by panel{Colors.ENDC}")
    elif act == "set_threads":
        try:
            t = max(1, min(50, int(cmd.get("threads") or 10)))
            WORKER_THREADS = t
            _r().set("threads:" + WORKER_ID, t)
            print(f"{Colors.OKCYAN}[fleet] threads -> {t}{Colors.ENDC}")
        except Exception:
            pass
    elif act == "update":
        _self_update(cmd.get("url") or "", cmd.get("sha256") or "")


def _check_commands():
    r = _r()
    for key in ("cmd:" + WORKER_ID, "cmd:all"):
        while True:
            raw = r.rpop(key)
            if not raw:
                break
            try:
                _handle_command(json.loads(raw))
            except Exception as e:
                print(f"{Colors.WARNING}[fleet] bad command: {e}{Colors.ENDC}")


def command_loop():
    import time as _ct
    _ct.sleep(10)
    while True:
        try:
            _check_commands()
        except Exception:
            pass
        _ct.sleep(5)

# ══════════════════════════════════════════════════════════════════════════════
# BANDWIDTH SAVER: block heavy media resources + per-account bandwidth meter.
# Instagram pages pull megabytes of images/video/fonts per account; blocking
# them cuts page weight ~70-85% with zero impact on login/OTP logic.
# Toggle: set env BW_SAVER=0 to disable entirely (blocking + meter).
# Debug:  set env BW_DEBUG=1 to log every blocked request URL (flow verification).
# ══════════════════════════════════════════════════════════════════════════════
_BW_BLOCK_TYPES = {"image", "media", "font"}
_BW_BLOCK_URL_SUBSTR = (
    "analytics",
    "graph.instagram",
    "connect.facebook.net",
)
_BW_DEBUG = os.environ.get("BW_DEBUG", "0") == "1"

async def _install_bandwidth_saver(context, page):
    """Attach route-level media blocking + CDP byte counter. Returns stats dict."""
    stats = {"bytes": 0, "requests": 0, "blocked": 0}
    if os.environ.get("BW_SAVER", "1") == "0":
        return stats

    async def _bw_route(route):
        req = route.request
        url = req.url.lower()
        if req.resource_type in _BW_BLOCK_TYPES or any(s in url for s in _BW_BLOCK_URL_SUBSTR):
            stats["blocked"] += 1
            if _BW_DEBUG:
                print(f"[BW-DEBUG] blocked {req.resource_type:6s} {req.url[:160]}", flush=True)
            await route.abort()
        else:
            await route.continue_()

    await context.route("**/*", _bw_route)

    # Accurate on-wire byte counting via CDP Network.loadingFinished
    # (encodedDataLength = bytes actually transferred, post-compression).
    try:
        cdp = await context.new_cdp_session(page)
        await cdp.send("Network.enable")

        def _on_finished(params):
            stats["bytes"] += int(params.get("encodedDataLength", 0) or 0)
            stats["requests"] += 1

        cdp.on("Network.loadingFinished", _on_finished)
        stats["_cdp"] = cdp  # keep a ref so the session isn't GC'd
    except Exception as e:
        print(f"[BW] meter unavailable ({e}); media blocking still active")
    return stats


def _print_bandwidth_report(email, stats):
    kb = stats["bytes"] / 1024
    mb = kb / 1024
    size = f"{mb:.2f} MB" if mb >= 1 else f"{kb:.0f} KB"
    print(f"[BW] {email}: {size} downloaded in {stats['requests']} requests, "
          f"{stats['blocked']} heavy requests blocked")


class TransientError(Exception):
    """Network-level failure worth retrying later on a fresh circuit (bounded)."""
    pass


_TRANSIENT_PATTERNS = (
    "ERR_HTTP_RESPONSE_CODE_FAILURE",
    "ERR_TIMED_OUT",
    "ERR_CONNECTION_CLOSED",
    "ERR_CONNECTION_RESET",
    "ERR_NETWORK_CHANGED",
    "ERR_INTERNET_DISCONNECTED",
    "ERR_TUNNEL_CONNECTION_FAILED",
    "ERR_NAME_NOT_RESOLVED",
    "net::",
)

def _is_transient_error(msg):
    m = str(msg or "")
    if any(p in m for p in _TRANSIENT_PATTERNS):
        return True
    # Playwright timeout: "Timeout 60000ms exceeded." / "Locator.fill: Timeout ..."
    # (str(e) me class name nahi hota, isliye plain "Timeout" check)
    if "Timeout" in m and "exceeded" in m:
        return True
    return False


async def _goto_with_retry(page, url, wait_until="domcontentloaded", timeout=60000, tries=3):
    """Goto with bounded retry for transient network failures.
    Raises TransientError (caller requeues) after tries are exhausted."""
    last = None
    for i in range(tries):
        try:
            await page.goto(url, wait_until=wait_until, timeout=timeout)
            return
        except Exception as e:
            last = e
            if _is_transient_error(str(e)) and i < tries - 1:
                print(f"[-] nav try {i+1}/{tries} transient fail, retrying: {str(e)[:130]}")
                try:
                    await page.wait_for_timeout(3000)
                except Exception:
                    pass
                continue
            raise
    raise TransientError(f"Navigation failed after {tries} tries: {last}")


async def _fill_login_form(page, email, password):
    """Language-independent login fill + verify every action (no fire-and-forget)."""
    # 1) username field — CSS first (language-independent), role fallback
    user_input = page.locator('input[name="username"]').first
    try:
        await user_input.wait_for(state="visible", timeout=30000)
    except Exception:
        user_input = page.get_by_role(
            "textbox", name=re.compile(r"username|email|mobile|phone", re.IGNORECASE)
        ).first
        await user_input.wait_for(state="visible", timeout=30000)
    await user_input.click()
    await user_input.fill(email)
    if (await user_input.input_value()).strip() != email.strip():
        await user_input.fill(email)  # one retry
        if (await user_input.input_value()).strip() != email.strip():
            raise Exception("Login fill verification failed: username field did not accept input")

    # 2) password field
    pass_input = page.locator('input[name="password"], input[type="password"]').first
    try:
        await pass_input.wait_for(state="visible", timeout=15000)
    except Exception:
        pass_input = page.get_by_role(
            "textbox", name=re.compile(r"password", re.IGNORECASE)
        ).first
        await pass_input.wait_for(state="visible", timeout=15000)
    await pass_input.click()
    await pass_input.fill(password)
    if not (await pass_input.input_value()):
        raise Exception("Login fill verification failed: password field did not accept input")

    # 3) submit — form submit button first (language-independent), role fallback
    submit = page.locator('form button[type="submit"]').first
    try:
        await submit.wait_for(state="visible", timeout=10000)
    except Exception:
        submit = page.get_by_role(
            "button", name=re.compile(r"log\s?in", re.IGNORECASE)
        ).first
        await submit.wait_for(state="visible", timeout=15000)
    await submit.click()
    print("[+] Login form filled + submit clicked (fill verified).")


async def _verify_2fa_enabled(page, instauser):
    """Independent positive check that 2FA is ON. True ONLY on confirmation."""
    try:
        await page.goto(
            "https://accountscenter.instagram.com/password_and_security/two_factor/",
            wait_until="domcontentloaded", timeout=60000,
        )
        await page.wait_for_timeout(4000)
        try:
            body = await page.locator("body").inner_text()
        except Exception:
            body = ""
        low = body.lower()
        if re.search(r"get started", low):
            print("[-] verify: 2FA page still shows 'Get started' -> NOT enabled")
            return False
        if "authentication app" in low and (
            "turn off" in low or re.search(r"\bon\b", low) or "enabled" in low
        ):
            print("[+] verify: 2FA positively confirmed enabled (authentication app on)")
            return True
        print("[-] verify: could not positively confirm 2FA is enabled")
        return False
    except Exception as e:
        print(f"[-] verify: check failed: {str(e)[:150]}")
        return False


async def process_account(context, page, email, password, qid=None):
    print(f"\n{Colors.OKBLUE}{Colors.BOLD}========================================={Colors.ENDC}")
    print(f"{Colors.OKBLUE}{Colors.BOLD}        STARTING ACCOUNT: {email}{Colors.ENDC}")
    print(f"{Colors.OKBLUE}{Colors.BOLD}========================================={Colors.ENDC}")

    seen_ids = set()
    # Prefetch existing emails so we don't accidentally grab an old OTP
    await asyncio.to_thread(prefetch_seen_ids, email, seen_ids)

    totp_secret = ""
    instauser = email.split('@')[0]
    
    proxy_country = "Unknown"
    proxy_ip = "Unknown"

    # ── Stage tracking: exact failure stage + timing, no guessing ──
    _stage_info = {"name": "init", "t0": time.monotonic()}
    def _set_stage(name):
        el = time.monotonic() - _stage_info["t0"]
        if _stage_info["name"] != "init":
            print(f"[stage] {_stage_info['name']}: {el:.1f}s")
        _stage_info["name"] = name
        _stage_info["t0"] = time.monotonic()

    try:
        _set_stage("proxy_check")
        print("[*] Checking proxy connection and country...")
        try:
            await page.goto("http://ip-api.com/json/", wait_until="domcontentloaded", timeout=15000)
            content = await page.locator("body").inner_text()
            ip_data = json.loads(content)
            if ip_data.get('status') == 'success':
                proxy_country = ip_data.get('country', 'Unknown')
                proxy_ip = ip_data.get('query', 'Unknown')
                print(f"{Colors.OKGREEN}[+] Connected to Proxy: {proxy_country} (IP: {proxy_ip}){Colors.ENDC}")
            else:
                print("[-] Could not parse proxy country.")
        except Exception as e:
            print(f"[-] Proxy check failed or timed out (continuing anyway).")

        _set_stage("nav_login")
        print(f"[*] Navigating to Instagram...")
        await _goto_with_retry(page, "https://www.instagram.com/accounts/login/?mtn#",
                               wait_until="domcontentloaded", timeout=60000, tries=3)

        # Wait a moment for page JS and GDPR init_script to kick in
        await page.wait_for_timeout(3000)

        # Fallback: manually dismiss GDPR popup if init_script hasn't fired yet
        try:
            cookie_btn = page.locator("button").filter(
                has_text=re.compile(r'Allow all cookies|Accept All', re.IGNORECASE)
            ).first
            if await cookie_btn.is_visible(timeout=5000):
                await cookie_btn.click()
                print("[*] Dismissed GDPR cookie popup.")
                await page.wait_for_timeout(1500)
        except Exception:
            pass

        # Explicitly wait for login form to be visible before trying to fill
        _set_stage("fill_login")
        print(f"[*] Waiting before filling credentials...")
        await _fill_login_form(page, email, password)

        
        # STEP 4: Smart Polling for Login Outcome (Success, Error, Checkpoint)
        _set_stage("login_poll")
        print(f"[*] Waiting for login to process and checking outcome...")
        
        # Smart polling loop for up to 20 seconds to see where we landed
        login_outcome = "unknown"
        for _ in range(10):
            if await page.get_by_text("Sorry, your password was incorrect").first.is_visible() or await page.get_by_text("The password you entered is incorrect").first.is_visible():
                raise Exception("Incorrect password.")
                
            if await page.get_by_text("Can't find account").first.is_visible():
                raise Exception("Account not found (Can't find account).")
                
            if await page.get_by_text("There was a problem logging you into Instagram").first.is_visible():
                raise Exception("Login failed: Problem logging in (block)")

            if await page.get_by_text("No Instagram profile found").first.is_visible():
                print("[*] No Instagram profile found popup detected. Assuming Meta account login is successful.")
                login_outcome = "meta_success"
                break
                
            if await page.get_by_text("Check your email").first.is_visible() or await page.get_by_text("Enter code").first.is_visible() or await page.get_by_text("Log in on another device").first.is_visible():
                print(f"[*] Account hit a checkpoint ('Check email' / 'Another device'). Reporting to panel and skipping.")
                report_result("saved_checkpoint", qid, {"username": instauser, "password": password, "email": email, "country": proxy_country, "ip": proxy_ip})
                raise Exception("Skipped: Verification checkpoint detected.")
                
            if await page.get_by_role("button", name="View Meta account details for").first.is_visible():
                print("[*] Found 'View Meta account details' button. Meta login successful.")
                login_outcome = "meta_success"
                break
                
            # If we see the Not Now button, it usually means we successfully logged in
            if await page.locator("button, div[role='button']").filter(has_text=re.compile(r'^Not now$', re.IGNORECASE)).first.is_visible():
                print("[*] Found 'Not Now' button. Instagram login successful.")
                login_outcome = "insta_success"
                break
                
            await page.wait_for_timeout(2000)

        # STEP 5: Dismiss Popups
        try:
            not_now_btn = page.locator("button, div[role='button']").filter(has_text=re.compile(r'^Not now$', re.IGNORECASE)).first
            if await not_now_btn.is_visible(timeout=3000):
                await not_now_btn.click()
                print("[*] Dismissed 'Not Now' popup.")
        except:
            pass
            
        try:
            cancel_btn = page.locator("button, div[role='button']").filter(has_text=re.compile(r'^Cancel$', re.IGNORECASE)).first
            if await cancel_btn.is_visible(timeout=2000):
                await cancel_btn.click()
                print("[*] Dismissed 'Cancel' popup.")
        except:
            pass
            
        is_email_checkpoint = False
        if not is_email_checkpoint:
            # Attempt to extract username from screen
            try:
                uname_input = page.locator('input[aria-label="Username"], input[type="text-no_suggestion"]')
                if await uname_input.is_visible(timeout=5000):
                    extracted_val = await uname_input.input_value()
                    if extracted_val:
                        instauser = extracted_val
                        print(f"[+] Extracted Username: {instauser}")
            except Exception:
                pass

        # Wait for either 'View Meta account details' OR the home page
        _set_stage("meta_setup")
        try:
            btn_meta = page.get_by_role("button", name="View Meta account details for")
            await expect(btn_meta).to_be_visible(timeout=30000)
            await btn_meta.click()
            
            # Setup Full Name
            full_name = generate_random_name()
            print(f"[*] Setting Full Name: {full_name}")
            await expect(page.get_by_role("textbox", name="Full name")).to_be_visible(timeout=30000)
            await page.get_by_role("textbox", name="Full name").fill(full_name)
            await page.get_by_role("button", name="Next").click()

            # Create username step
            username_field = page.get_by_label("Create a username")
            if not await username_field.is_visible(timeout=5000):
                username_field = page.locator('input[aria-label="Username"]')
            
            await expect(username_field).to_be_visible(timeout=30000)
            
            # Extract the actual username
            try:
                extracted = ""
                # Try specific input locator first
                uname_input = page.locator('input[aria-label="Username"], input[type="text-no_suggestion"]')
                if await uname_input.is_visible(timeout=2000):
                    extracted = await uname_input.input_value()
                
                if not extracted:
                    extracted = await username_field.input_value(timeout=2000)
                    
                if not extracted:
                    username_span = page.locator("span").filter(has_text=re.compile(r"^Username$", re.IGNORECASE)).first
                    parent_text = await username_span.locator("..").inner_text(timeout=2000)
                    parts = parent_text.split('\n')
                    if len(parts) > 1:
                        extracted = parts[1].strip()
                        
                if extracted:
                    instauser = extracted
                    print(f"[+] Extracted generated Username: {instauser}")
                else:
                    print(f"[-] Failed to extract username from DOM")
            except Exception as ex:
                print(f"[-] Exception during username extraction: {ex}")
                pass
                
            print(f"[*] Confirming Username...")
            await page.get_by_role("button", name="Next").click()

            # Terms and conditions
            await expect(page.get_by_label("To create an Instagram")).to_be_visible(timeout=30000)
            print(f"[*] Accepting Instagram Terms...")
            await page.get_by_role("button", name="Allow and continue").click()
            
            await expect(page.get_by_label("Agree to Instagram's terms")).to_be_visible(timeout=30000)
            await page.get_by_role("button", name="I agree").click()
            
            print(f"[*] Waiting for registration to complete (URL check)...")
            try:
                await page.wait_for_url("**/accounts/registered/**", timeout=180000)
                print(f"[*] Registration flow completed.")
                registration_success = True
            except Exception as url_err:
                print(f"[-] Registration URL not found (timeout). Account may not be fully registered.")
                registration_success = False
                
        except Exception as e:
            # Don't mask real setup failures as "already registered".
            if login_outcome in ("insta_success", "meta_success"):
                print(f"[*] Meta profile setup not needed ({login_outcome}). Proceeding to 2FA. (setup note: {str(e)[:150]})")
                registration_success = True  # Already registered / existing account - proceed to 2FA
            else:
                raise Exception(f"Meta setup failed and login state was '{login_outcome}': {str(e)[:200]}")
            
        # If registration failed (URL not found), save to separate file and skip 2FA
        if not registration_success:
            print(f"[!] Skipping 2FA for {email} — registration not confirmed. Reporting to panel.")
            report_result("saved_needs_2fa", qid, {"username": instauser, "password": password, "email": email, "country": proxy_country, "ip": proxy_ip})
            return
            
        # If is_email_checkpoint is True, we skipped the Meta flow and landed here directly.

        # Go to Accounts Center 2FA page directly
        _set_stage("nav_2fa")
        print(f"[*] Navigating to 2FA setup in Accounts Center...")

        try:
            await _goto_with_retry(page, "https://accountscenter.instagram.com/password_and_security/two_factor/",
                                   wait_until="domcontentloaded", timeout=60000, tries=3)
            await page.wait_for_timeout(3000) # Give it a little time to load
        except TransientError:
            raise
        except Exception as e:
            print(f"[-] Warning: Navigation to Accounts Center may have timed out: {e}")
        
        # Extension (free vpn) auto-accepts GDPR cookies — no manual click needed
        
        # If it asks to select an account (list item containing the username)
        try:
            print(f"[DEBUG] Checking for account button: {instauser}")
            account_btn = page.get_by_text(instauser)
            if await account_btn.is_visible(timeout=60000):
                print(f"[DEBUG] Found account button. Clicking...")
                await account_btn.click()
            else:
                print(f"[DEBUG] Account button not found within timeout.")
        except Exception as e:
            print(f"[DEBUG] Error checking for account button: {e}")

        # Sometimes it asks to 'Get started' or 'Continue' or 'Next'
        try:
            print(f"[DEBUG] STRICTLY waiting for Get started/Continue/Next button...")
            start_btn = page.get_by_role("button", name=re.compile(r'^Get started$|^Continue$|^Next$', re.IGNORECASE)).first
            email_heading = page.get_by_role("heading", name=re.compile(r"Check your email|Enter the code", re.IGNORECASE))
            auth_app_header = page.get_by_text("Help protect your account", exact=False).first
            
            for _ in range(15): # Max ~60 seconds total wait
                if await start_btn.is_visible(timeout=5000):
                    print(f"[DEBUG] Found start/continue button. Clicking...")
                    await start_btn.click()
                    print(f"[DEBUG] Waiting for full load after clicking...")
                    try:
                        await page.wait_for_load_state("networkidle", timeout=60000)
                    except Exception as e:
                        print(f"[DEBUG] Wait for networkidle timed out or failed: {e}")
                    break
                elif await email_heading.is_visible(timeout=1000) or await auth_app_header.is_visible(timeout=1000):
                    print(f"[DEBUG] Page skipped to next step (Email OTP or Auth App header found). Moving forward!")
                    break
                else:
                    print(f"[DEBUG] Still strictly waiting for Get started/Continue/Next button...")
                    await page.wait_for_timeout(2000)
            else:
                # If loop finishes without breaking (i.e. no button found after 15 attempts)
                print(f"[!] Timeout waiting for Accounts Center. Reporting to panel and skipping.")
                report_result("saved_needs_2fa", qid, {"username": instauser, "password": password, "email": email, "country": proxy_country, "ip": proxy_ip})
                return
        except Exception as e:
            print(f"[DEBUG] Error during strict wait for start/continue button: {e}")
            print(f"[!] Reporting to panel and skipping due to error.")
            report_result("saved_needs_2fa", qid, {"username": instauser, "password": password, "email": email, "country": proxy_country, "ip": proxy_ip})
            return

 
        # Handle Email OTP if requested by Meta before allowing 2FA setup
        _set_stage("email_otp")
        email_otp_required = False
        email_otp_error = None
        try:
            print(f"[DEBUG] Checking if Meta is asking for Email OTP...")
            # Check for "Check your email" or similar text
            is_email_check = False
            try:
                print(f"[DEBUG] Waiting for 'Check your email' or 'Enter the code' text...")
                # We will check if any visible element contains these texts, or if the heading exists
                email_heading = page.get_by_role("heading", name=re.compile(r"Check your email|Enter the code", re.IGNORECASE))
                if await email_heading.is_visible(timeout=155000) or await page.locator(':has-text("Check your email"):visible').last.is_visible(timeout=5000):
                    is_email_check = True
                    print(f"[DEBUG] Found 'Check your email' or 'Enter the code' text!")
                else:
                    print(f"[DEBUG] Did not find 'Check your email' text.")
            except Exception as e:
                print(f"[DEBUG] Error checking email text: {e}")
                
            print(f"[DEBUG] Looking for visible OTP input field...")
            # Grab the first VISIBLE input field or placeholder "Code"
            code_input = page.get_by_placeholder(re.compile(r"code", re.IGNORECASE))
            if not await code_input.is_visible(timeout=5000):
                code_input = page.locator('input:visible').first
                
            if is_email_check or await code_input.is_visible(timeout=15000):
                email_otp_required = True
                print(f"[*] Meta is requesting an Email OTP before 2FA.")
                print(f"[*] Fetching OTP for {email} (Waiting up to 60s)...")
                otp = await asyncio.to_thread(fetch_otp, email, seen_ids, max_retries=12)
                
                if not otp:
                    print(f"[-] No OTP received after 1 minute. Attempting to resend...")
                    try:
                        resend_btn = page.locator("text=Get a new code")
                        if not await resend_btn.is_visible(timeout=10000):
                            resend_btn = page.locator("text=send a new code")
                        if not await resend_btn.is_visible(timeout=10000):
                            resend_btn = page.locator("text=Resend")
                            
                        await resend_btn.click(timeout=15000)
                        print(f"[*] Clicked resend. Waiting another 60s for new OTP...")
                        otp = await asyncio.to_thread(fetch_otp, email, seen_ids, max_retries=12)
                    except Exception as e:
                        print(f"[-] Could not find or click resend button: {e}")
                
                if otp:
                    print(f"[+] Received OTP: {otp}")
                    await code_input.fill(otp)
                    # Use a generic Continue/Submit
                    submit_btn = page.locator("button, div[role='button']").filter(has_text=re.compile(r'Continue|Submit|Next', re.IGNORECASE)).first
                    if await submit_btn.is_visible(timeout=15000):
                        await submit_btn.click()
                    else:
                        await page.keyboard.press("Enter")
                    
                    # Wait a moment for it to process
                    await page.wait_for_timeout(5000)
                    
                    # Check if error message appeared
                    error_msg = page.locator("text=This code doesn't work")
                    if await error_msg.is_visible(timeout=3000):
                        print("[-] Code was incorrect. Checking if a newer OTP has already arrived (waiting up to 20s)...")
                        
                        # First wait without clicking resend (in case it was just delayed)
                        new_otp = await asyncio.to_thread(fetch_otp, email, seen_ids, max_retries=4) # 4 * 5 = 20s
                        
                        if not new_otp:
                            print("[-] No new OTP arrived. Clicking 'Get a new code' to resend...")
                            new_code_btn = page.locator("text=Get a new code")
                            if await new_code_btn.is_visible(timeout=5000):
                                await new_code_btn.click()
                                print("[*] Clicked 'Get a new code', waiting 60s for new OTP...")
                                new_otp = await asyncio.to_thread(fetch_otp, email, seen_ids, max_retries=12)
                                
                        if new_otp:
                            print(f"[+] Received NEW OTP: {new_otp}")
                            await code_input.fill(new_otp)
                            if await submit_btn.is_visible(timeout=5000):
                                await submit_btn.click()
                            else:
                                await page.keyboard.press("Enter")
                            await page.wait_for_timeout(5000)
                        else:
                            raise Exception("Failed to fetch new Email OTP after incorrect code.")
                else:
                    raise Exception("Failed to fetch Email OTP even after resend attempt.")
        except Exception as e:
            # Don't swallow: record the real OTP failure instead of silently continuing.
            email_otp_error = str(e)[:200]
            print(f"[-] Email OTP stage failed: {email_otp_error}")

        if email_otp_required and email_otp_error:
            raise Exception(f"Email OTP required but failed: {email_otp_error}")

        # ─── STAGE TRACKING FLAGS ─────────────────────────────────────────
        totp_secret = ""        # Set once TOTP key is captured
        enter_code_success = False  # Set once code is submitted to Instagram
        confirmation_success = False  # Set once 2FA enablement is positively confirmed

        # Choose 'Authentication app' method
        _set_stage("select_auth_app")
        try:
            print(f"[*] Selecting 'Authentication app' method...")
            print(f"[DEBUG] Checking for 'Help protect your account' header...")
            try:
                if await expect(page.get_by_text("Help protect your account", exact=False).first).to_be_visible(timeout=60000):
                    print(f"[DEBUG] Found 'Help protect your account' header.")
            except Exception as e:
                print(f"[DEBUG] 'Help protect your account' header not found: {e}")
                
            print(f"[DEBUG] Looking for Continue or Next button for Auth app...")
            next_btn = page.get_by_text("Continue", exact=True).first
            if not await next_btn.is_visible(timeout=5000):
                next_btn = page.get_by_text("Next", exact=True).first
                
            if await next_btn.is_visible(timeout=60000):
                await next_btn.click()
                print("[*] Clicked Continue/Next for Authentication app.")
            else:
                print("[-] Could not find Continue button!")
        except Exception as e:
            print(f"[-] Error selecting Authentication app method: {e}")

        # Wait and Extract key directly from DOM
        _set_stage("capture_totp")
        print(f"[*] Waiting for 'Instructions for setup' and 'Copy' to appear...")
        
        try:
            await expect(page.get_by_text("Instructions for setup", exact=True).first).to_be_visible(timeout=60000)
            
            # Check for Something went wrong popup
            err_dialog = page.get_by_text("Something went wrong", exact=True).first
            if await err_dialog.is_visible(timeout=2000):
                print("[-] 'Something went wrong' popup detected! Trying to recover...")
                try:
                    await page.get_by_role("button", name="OK").click(timeout=3000)
                except:
                    pass
                
                print("[*] Navigating to Home to clear state...")
                await page.goto("https://www.instagram.com/", wait_until="networkidle", timeout=60000)
                try:
                    dismiss_btn = page.locator("button, div[role='button']").filter(has_text=re.compile(r'Dismiss', re.IGNORECASE)).first
                    if await dismiss_btn.is_visible(timeout=5000):
                        await dismiss_btn.click()
                        print("[*] Clicked Dismiss.")
                except:
                    pass
                    
                print("[*] Restarting 2FA setup flow...")
                await page.goto("https://accountscenter.instagram.com/password_and_security/two_factor/", wait_until="networkidle", timeout=60000)

                try:
                    account_btn = page.get_by_text(instauser)
                    if await account_btn.is_visible(timeout=60000):
                        await account_btn.click()
                except:
                    pass
                    
                try:
                    start_btn = page.get_by_role("button", name=re.compile(r'^Get started$|^Continue$|^Next$', re.IGNORECASE)).first
                    if await start_btn.is_visible(timeout=60000):
                        await start_btn.click()
                except:
                    pass
                
                await expect(page.get_by_text("Instructions for setup", exact=True).first).to_be_visible(timeout=60000)
            
            copy_btn = page.locator("text=Copy").first
            if await copy_btn.is_visible(timeout=5000):
                print("[*] 'Copy' button is visible, key should be fully loaded.")
        except Exception:
            pass
            
        print(f"[*] Extracting 16-character 2FA key from DOM...")
        
        for _ in range(30):
            try:
                spans = await page.locator("span").all_inner_texts()
                for text in spans:
                    clean_text = text.strip()
                    if len(clean_text) == 19 and re.match(r'^[A-Z2-7]{4}\s[A-Z2-7]{4}\s[A-Z2-7]{4}\s[A-Z2-7]{4}$', clean_text, re.IGNORECASE):
                        totp_secret = clean_text.replace(' ', '').upper()
                        print(f"[+] Found key from span text: {totp_secret}")
                        break
            except Exception:
                pass
                
            if totp_secret:
                break
                
            await page.wait_for_timeout(1000)

        if not totp_secret:
            # ── CASE 1: TOTP key nahi mila = No 2FA applied ──────────────────
            print(f"[-] Could not capture TOTP key. Reporting to panel.")
            report_result("saved_no_2fa", qid, {"username": instauser, "password": password, "email": email, "country": proxy_country, "ip": proxy_ip})
            return
            
        print(f"{Colors.OKGREEN}[+] Captured TOTP Secret: {totp_secret}{Colors.ENDC}")

        print("[*] Waiting 3 seconds for the page to stabilize before proceeding...")
        await page.wait_for_timeout(4000)

        # Click Next / Enter code button
        try:
            next_btn = page.get_by_text("Next", exact=True).first
            if not await next_btn.is_visible(timeout=60000):
                next_btn = page.get_by_role("button", name="Next").first
                
            if await next_btn.is_visible(timeout=60000):
                await next_btn.click()
            else:
                print("[-] Next button not found, trying Enter code...")
                enter_code_btn = page.get_by_role("button", name="Enter code").first
                if await enter_code_btn.is_visible(timeout=60000):
                    await enter_code_btn.click()
        except Exception as e:
            print(f"[-] Could not click Next/Enter code: {e}")
        
        # Generate TOTP code and enter it
        _set_stage("enter_code")
        totp = pyotp.TOTP(totp_secret)
        auth_code = totp.now()
        print(f"[*] Generated Auth Code: {auth_code}")
        
        try:
            code_input = page.get_by_role("textbox", name="Enter code")
            await expect(code_input).to_be_visible(timeout=60000)
            await code_input.fill(auth_code)
            await page.get_by_role("button", name="Next").click()
            enter_code_success = True
        except Exception as e:
            # ── CASE 2: Enter code step failed = TOTP key acquired but code submit failed
            print(f"[-] Failed at Enter Code step: {e}")
            print(f"[!] Reporting to panel with TOTP key")
            report_result("saved_enter_code_failed", qid, {"username": instauser, "password": password, "totp": totp_secret, "email": email, "country": proxy_country, "ip": proxy_ip})
            return

        # Wait for success confirmation dialog — then VERIFY, never assume.
        _set_stage("confirm")
        print(f"[*] Waiting for confirmation...")
        try:
            await expect(page.get_by_role("dialog", name="Your two-factor")).to_be_visible(timeout=60000)
            await page.get_by_role("button", name="Done").click(timeout=5000)
            confirmation_success = True
        except Exception:
            # Dialog missing: verify 2FA state directly instead of assuming success.
            print("[*] Confirmation dialog not found — verifying 2FA state directly...")
            confirmation_success = await _verify_2fa_enabled(page, instauser)

        if not confirmation_success:
            print("[-] 2FA enablement NOT confirmed — reporting as enter_code_failed (NOT success).")
            report_result("saved_enter_code_failed", qid, {"username": instauser, "password": password, "totp": totp_secret, "email": email, "country": proxy_country, "ip": proxy_ip, "note": "code submitted but 2FA enablement not confirmed"})
            return

        print(f"{Colors.OKGREEN}{Colors.BOLD}[+] Successfully enabled 2FA for {email}! (verified){Colors.ENDC}")
        
        # Report success to panel (panel ingests -> SQLite -> Google Sheets in real time)
        report_result("success", qid, {"username": instauser, "password": password, "totp": totp_secret, "email": email, "country": proxy_country, "ip": proxy_ip})
            
    except TransientError:
        # Network-level failure: let the caller requeue for a fresh circuit.
        # Do NOT report as final error here.
        raise
    except Exception as e:
        _el = time.monotonic() - _stage_info["t0"]
        print(f"{Colors.FAIL}[!] Error processing {email} at stage [{_stage_info['name']}] (+{_el:.0f}s): {e}{Colors.ENDC}")
        # Cookies bhi save karo (original bot ki tarah error_new.txt me the)
        try:
            _cookies = await context.cookies()
            cookie_string = ";".join([f"{c['name']}={c['value']}" for c in _cookies])
        except Exception as ce:
            print(f"[-] Could not grab cookies for {email}: {ce}")
            cookie_string = ""
        report_result("error", qid, {"username": instauser, "password": password, "email": email,
                                     "country": proxy_country, "ip": proxy_ip,
                                     "cookies": cookie_string,
                                     "stage": _stage_info["name"],
                                     "error": f"[{_stage_info['name']}] {str(e)[:300]}"})
        

    finally:
        await context.close()


async def start_local_proxy(tor_port, username, password):
    async def handle_client(reader, writer):
        try:
            version, nmethods = struct.unpack("!BB", await reader.readexactly(2))
            await reader.readexactly(nmethods)
            writer.write(b"\x05\x00")
            await writer.drain()

            req_header = await reader.readexactly(4)
            version, cmd, _, address_type = struct.unpack("!BBBB", req_header)
            
            if address_type == 1:
                addr_data = await reader.readexactly(4)
            elif address_type == 3:
                domain_len = (await reader.readexactly(1))[0]
                addr_data = struct.pack("!B", domain_len) + await reader.readexactly(domain_len)
            elif address_type == 4:
                addr_data = await reader.readexactly(16)
            else:
                writer.close()
                return
                
            port_data = await reader.readexactly(2)

            tor_reader, tor_writer = await asyncio.open_connection("127.0.0.1", tor_port)
            
            tor_writer.write(b"\x05\x01\x02")
            await tor_writer.drain()
            tor_greeting_resp = await tor_reader.readexactly(2)
            if tor_greeting_resp[1] != 2:
                writer.close()
                return
                
            u, p = username.encode(), password.encode()
            auth_req = struct.pack("!BB", 1, len(u)) + u + struct.pack("!B", len(p)) + p
            tor_writer.write(auth_req)
            await tor_writer.drain()
            
            auth_resp = await tor_reader.readexactly(2)
            if auth_resp[1] != 0:
                writer.close()
                return
                
            tor_writer.write(req_header + addr_data + port_data)
            await tor_writer.drain()
            
            tor_resp_header = await tor_reader.readexactly(4)
            _, rep, _, tor_atyp = struct.unpack("!BBBB", tor_resp_header)
            
            if tor_atyp == 1:
                tor_addr_data = await tor_reader.readexactly(4)
            elif tor_atyp == 3:
                tor_dlen = (await tor_reader.readexactly(1))[0]
                tor_addr_data = struct.pack("!B", tor_dlen) + await tor_reader.readexactly(tor_dlen)
            elif tor_atyp == 4:
                tor_addr_data = await tor_reader.readexactly(16)
                
            tor_port_data = await tor_reader.readexactly(2)
            
            writer.write(tor_resp_header + tor_addr_data + tor_port_data)
            await writer.drain()
            
            if rep != 0:
                writer.close()
                tor_writer.close()
                return
                
            async def pump(r, w):
                try:
                    while True:
                        data = await r.read(32768)
                        if not data: break
                        w.write(data)
                        await w.drain()
                except (ConnectionResetError, ConnectionAbortedError, BrokenPipeError, OSError):
                    pass
                except Exception:
                    pass
                finally:
                    try:
                        if not w.is_closing():
                            w.close()
                            await asyncio.wait_for(w.wait_closed(), timeout=2)
                    except Exception:
                        pass
                        
            await asyncio.gather(pump(reader, tor_writer), pump(tor_reader, writer))
        except (ConnectionResetError, ConnectionAbortedError, BrokenPipeError, OSError):
            pass
        except Exception:
            pass
        finally:
            try:
                if not writer.is_closing():
                    writer.close()
                    await asyncio.wait_for(writer.wait_closed(), timeout=2)
            except Exception:
                pass

    server = await asyncio.start_server(handle_client, '127.0.0.1', 0)
    port = server.sockets[0].getsockname()[1]
    return server, port

# ── Circuit speed gate: "ek dam slow ho gya" ka permanent fix ─────────────────
# Har account se PEHLE circuit ko www.instagram.com:443 tak probe karo.
# Slow circuit (>CIRCUIT_MAX_S) mile to turant naya auth = naya Tor circuit.
# Dheeme circuit par bhari browser kholne se achha hai 10-20s me tez
# circuit dhoondh lena — yehi flush ke baad tez chalne ka asli raaz tha
# (fresh Tor = fresh tez circuits), ab har account par wahi milega.
CIRCUIT_MAX_S = 12   # seconds: isse slow circuit reject
CIRCUIT_TRIES = 4    # ek account ke liye max kitne circuits try kare

async def _circuit_connect_time(local_port, timeout=12):
    """Local proxy se www.instagram.com:443 tak SOCKS CONNECT me kitne sec lage.
    Fail/timeout par inf — yehi slow/dead circuit ki pehchan hai."""
    import time as _t
    t0 = _t.monotonic()
    try:
        reader, writer = await asyncio.wait_for(
            asyncio.open_connection("127.0.0.1", local_port), timeout=timeout)
        try:
            writer.write(b"\x05\x01\x00"); await writer.drain()
            if await asyncio.wait_for(reader.readexactly(2), timeout=timeout) != b"\x05\x00":
                return float("inf")
            host = b"www.instagram.com"
            writer.write(b"\x05\x01\x00\x03" + bytes([len(host)]) + host + struct.pack("!H", 443))
            await writer.drain()
            rep = await asyncio.wait_for(reader.readexactly(4), timeout=timeout)
            if rep[1] != 0:
                return float("inf")
            atyp = rep[3]
            if atyp == 1:
                await asyncio.wait_for(reader.readexactly(6), timeout=timeout)
            elif atyp == 3:
                ln = (await asyncio.wait_for(reader.readexactly(1), timeout=timeout))[0]
                await asyncio.wait_for(reader.readexactly(ln + 2), timeout=timeout)
            elif atyp == 4:
                await asyncio.wait_for(reader.readexactly(18), timeout=timeout)
            else:
                return float("inf")
            return _t.monotonic() - t0
        finally:
            writer.close()
    except Exception:
        return float("inf")

async def _fast_circuit_proxy():
    """Tez Tor circuit wala local proxy lao; slow mile to naya try.
    Returns (proxy_server, local_port) — bilkul purane pattern jaisa."""
    for attempt in range(1, CIRCUIT_TRIES + 1):
        auth = "".join(random.choices(string.ascii_letters + string.digits, k=10))
        server, port = await start_local_proxy(TOR_PORT, auth, auth)
        secs = await _circuit_connect_time(port)
        if secs <= CIRCUIT_MAX_S:
            if attempt > 1:
                print(f"circuit OK ({secs:.1f}s, try {attempt}/{CIRCUIT_TRIES})")
            return server, port
        try:
            server.close()
            await asyncio.wait_for(server.wait_closed(), timeout=3)
        except Exception:
            pass
        print(f"slow circuit ({secs:.1f}s>{CIRCUIT_MAX_S}s) — naya circuit try {attempt}/{CIRCUIT_TRIES}")
        await asyncio.sleep(1)
    print("saare circuits slow mile — aakhri wala hi use kar rahe hain (kaam rukega nahi)")
    auth = "".join(random.choices(string.ascii_letters + string.digits, k=10))
    return await start_local_proxy(TOR_PORT, auth, auth)

async def run(playwright: Playwright) -> None:
    print(f"[*] {WORKER_ID}: claiming accounts from Redis queue ({REDIS_URL})")
    print(f"[*] Starting in Tor IP mode (port {TOR_PORT})...")

    # Threads: --threads flag > Redis fleet default > 10
    # Har thread BILKUL independent hai — koi batch system nahi. Ek thread ka
    # account khatam hote hi wo turant next claim karta hai, doosron ka wait kiye bina.
    max_threads = WORKER_THREADS
    print(f"{Colors.OKCYAN}[*] {WORKER_ID}: using {max_threads} independent threads (back-to-back, no batches).{Colors.ENDC}")

    async def process_single_account(raw, item):
        email, password, qid = item["email"], item["password"], item.get("qid", 0)
        global CURRENT_EMAIL
        CURRENT_EMAIL = "[%s] %s" % (_worker_tag.get() or "?", email)
        # Create a temporary directory for the persistent context (fresh state for each account)
        user_data_dir = tempfile.mkdtemp()

        try:
            # GCloud/Linux browser args (supports extensions using new headless mode)
            browser_args = [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu",
                "--disable-setuid-sandbox",
                f"--disable-extensions-except={EXTENSION_PATH}",
                f"--load-extension={EXTENSION_PATH}",
            ]
            if HEADLESS_MODE:
                browser_args.append("--headless=new")

            # Circuit gate: slow Tor circuit mile to turant naya lo (neeche _fast_circuit_proxy).
            # Har thread ka apna unique auth = unique Tor circuit = unique IP (pehle jaisa hi).
            proxy_server, local_port = await _fast_circuit_proxy()
            tor_proxy = {"server": f"socks5://127.0.0.1:{local_port}"}

            context = await playwright.chromium.launch_persistent_context(
                user_data_dir,
                headless=False, # Must be False for extensions; --headless=new in args overrides this cleanly
                user_agent="Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36",
                viewport={'width': 412, 'height': 915},
                is_mobile=True,
                has_touch=True,
                permissions=['clipboard-read', 'clipboard-write'],
                args=browser_args,
                proxy=tor_proxy
            )

            # Persistent context comes with an initial page
            page = context.pages[0] if context.pages else await context.new_page()

            # Apply stealth mode to bypass bot detection
            await Stealth().apply_stealth_async(page)

            # Bandwidth saver: block heavy media (image/video/font) + meter per-account usage
            bw_stats = await _install_bandwidth_saver(context, page)

            # Wait a moment
            await page.wait_for_timeout(2000)

            try:
                await process_account(context, page, email, password, qid)
            except TransientError as te:
                # Bounded retry: transient network failure -> fresh circuit par dobara.
                # Max 2 requeue = 3 total attempts; uske baad final error.
                retries = int(item.get("_retries", 0) or 0)
                if retries < 2:
                    item["_retries"] = retries + 1
                    try:
                        _r().lpush("queue:pending", json.dumps(item))
                        print(f"{Colors.WARNING}[↻] {email}: transient ({str(te)[:100]}) — requeued, attempt {retries+2}/3{Colors.ENDC}")
                    except Exception as re:
                        print(f"[-] requeue failed: {re}")
                        raise Exception(f"Transient failure, requeue failed: {te}")
                else:
                    print(f"[-] {email}: transient failure on final attempt (3/3) — reporting error.")
                    raise Exception(f"Network failed after 3 attempts: {te}")
            finally:
                _print_bandwidth_report(email, bw_stats)

        finally:
            ack_claim(raw)  # release the Redis claim whatever happened
            # Clean up context and user data directory
            try:
                await context.close()
            except:
                pass

            try:
                if 'proxy_server' in locals():
                    proxy_server.close()
                    await proxy_server.wait_closed()
            except Exception as e:
                print(f"[-] Could not close local proxy: {e}")

            try:
                # Give the browser a second to fully release file locks before deleting
                await asyncio.sleep(1)
                shutil.rmtree(user_data_dir, ignore_errors=True)
            except Exception as e:
                print(f"[-] Could not delete temporary profile dir: {e}")

        # Back-to-back: koi delay nahi — thread turant next account lega

    print(f"{Colors.OKCYAN}[*] {WORKER_ID}: independent mode — har thread apna account khatam karke turant next lega (koi batch wait nahi).{Colors.ENDC}")

    loop = asyncio.get_running_loop()
    claim_pool = ThreadPoolExecutor(max_workers=max_threads)
    # Auto-renew state: N accounts ya M ghante baad fresh Tor + fresh process.
    # NOTE: single event-loop thread hai, isliye lock ki zaroorat nahi.
    renew_state = {"done": 0, "start": time.monotonic(), "renew": False}

    def _renew_due():
        if renew_state["renew"]:
            return True
        elapsed_h = (time.monotonic() - renew_state["start"]) / 3600
        if (WORKER_RESTART_EVERY > 0 and renew_state["done"] >= WORKER_RESTART_EVERY) \
                or (WORKER_RESTART_HOURS > 0 and elapsed_h >= WORKER_RESTART_HOURS):
            renew_state["renew"] = True
            return True
        return False

    async def worker_loop(tag):
        # Is task ka naam set karo — iske andar ke SAARE print() terminal me
        # [Tn] tag ke saath dikhenge (process_account ke andar wale bhi).
        _worker_tag.set(tag)
        print(f"{Colors.OKCYAN}[*] {tag}: started.{Colors.ENDC}")
        idle_rounds = 0
        while True:
            if _is_paused():
                await asyncio.sleep(10)
                continue
            if _renew_due():
                print(f"[*] {tag}: renew flagged — naya account nahi lunga, exiting.")
                return
            claimed = await loop.run_in_executor(claim_pool, claim_one)
            if claimed == "DOWN":
                print(f"{Colors.WARNING}[!] {tag}: Redis unreachable, retrying in 30s...{Colors.ENDC}")
                await asyncio.sleep(30)
                continue
            if claimed is None:
                idle_rounds += 1
                if idle_rounds >= 10:
                    print(f"\n{Colors.OKGREEN}{Colors.BOLD}[+] {tag}: queue empty for a while, shutting down.{Colors.ENDC}")
                    return
                await asyncio.sleep(10)
                continue
            if _renew_due():
                # Claim block ke dauraan renew flag lag gaya — account wapas queue me daalo, skip karo
                raw, item = claimed
                try:
                    _r().lpush("queue:pending", raw)
                except Exception:
                    pass
                ack_claim(raw)
                print(f"[*] {tag}: renew flagged — claimed account wapas queue me daal diya, exiting.")
                return
            idle_rounds = 0
            raw, item = claimed
            email = item.get("email", "?")
            print(f"{Colors.OKBLUE}{Colors.BOLD}[*] {tag}: claimed {email} — starting.{Colors.ENDC}")
            try:
                await process_single_account(raw, item)
            except Exception as e:
                print(f"{Colors.FAIL}[!] {tag}: UNCAUGHT error on {email}: {e}{Colors.ENDC}")
            print(f"{Colors.OKCYAN}[*] {tag}: finished {email} — next account (back-to-back).{Colors.ENDC}")
            renew_state["done"] += 1
            # NOTE: yahan koi sleep/delay nahi — loop turant next account claim karega

    tags = ["T%d" % (i + 1) for i in range(max_threads)]
    tasks = [asyncio.create_task(worker_loop(t), name=t) for t in tags]
    print(f"{Colors.OKCYAN}[*] {WORKER_ID}: {max_threads} independent threads live ({', '.join(tags)}) — koi thread kisi ka wait nahi karega.{Colors.ENDC}")
    await asyncio.gather(*tasks)
    claim_pool.shutdown(wait=False)

    if renew_state["renew"]:
        # Sab threads ka kaam khatam — ab renew safe hai (koi account in-flight nahi)
        done_n = renew_state["done"]
        elapsed_h = (time.monotonic() - renew_state["start"]) / 3600
        print(f"\n{Colors.OKCYAN}{Colors.BOLD}[*] {WORKER_ID}: {done_n} accounts / {elapsed_h:.1f}h ho gaye — renewing (fresh Tor + restart)...{Colors.ENDC}")
        sys.stdout.flush()
        _kill_own_chrome()
        await asyncio.to_thread(_restart_tor_fresh)
        print(f"{Colors.OKCYAN}[*] Restarting worker process...{Colors.ENDC}")
        sys.stdout.flush()
        await asyncio.sleep(1)
        os.execv(sys.executable, [sys.executable] + sys.argv)
    else:
        print(f"\n{Colors.OKGREEN}{Colors.BOLD}[+] {WORKER_ID}: all threads idle — queue empty, worker shutting down.{Colors.ENDC}")

def setup_tor():
    """
    Auto-install and configure Tor on Linux (Google Cloud Shell / Compute Engine).
    Ensures IsolateSOCKSAuth is set so each thread gets a unique IP.
    """
    # ── 1. Install Tor if missing ─────────────────────────────────────────
    if subprocess.run(["which", "tor"], capture_output=True).returncode != 0:
        print(f"{Colors.OKCYAN}[*] Tor not found. Installing via apt-get...{Colors.ENDC}")
        subprocess.run(["sudo", "apt-get", "update", "-y"], check=True)
        subprocess.run(["sudo", "apt-get", "install", "-y", "tor"], check=True)
        print(f"{Colors.OKGREEN}[+] Tor installed successfully.{Colors.ENDC}")
    else:
        print(f"{Colors.OKGREEN}[+] Tor is already installed.{Colors.ENDC}")

    # ── 2. Write torrc to enable IsolateSOCKSAuth ─────────────────────────
    torrc_content = """
# Auto-generated by insta_tor_ip_gclud.py
SocksPort 9050 IsolateSOCKSAuth
DataDirectory /var/lib/tor
Log notice stdout
"""
    torrc_path = "/etc/tor/torrc"
    try:
        with open(torrc_path, "w") as f:
            f.write(torrc_content)
        print(f"{Colors.OKGREEN}[+] torrc configured with IsolateSOCKSAuth.{Colors.ENDC}")
    except PermissionError:
        print(f"{Colors.WARNING}[!] Cannot write torrc directly — trying sudo tee...{Colors.ENDC}")
        proc = subprocess.Popen(
            ["sudo", "tee", torrc_path],
            stdin=subprocess.PIPE, stdout=subprocess.DEVNULL
        )
        proc.communicate(torrc_content.encode())

    # ── 3. Stop any existing Tor, then start fresh ───────────────────────
    print(f"{Colors.OKCYAN}[*] Starting Tor service...{Colors.ENDC}")
    subprocess.run(["sudo", "service", "tor", "stop"],  capture_output=True)
    subprocess.run(["sudo", "service", "tor", "start"], check=True)

    # ── 4. Wait until Tor is ready (bootstrapped) ────────────────────────
    print(f"{Colors.OKCYAN}[*] Waiting for Tor to bootstrap...{Colors.ENDC}")
    import time
    for attempt in range(30):
        try:
            test_sock = socket.create_connection(("127.0.0.1", 9050), timeout=2)
            test_sock.close()
            print(f"{Colors.OKGREEN}[+] Tor is ready on port 9050!{Colors.ENDC}")
            return
        except (ConnectionRefusedError, OSError):
            time.sleep(2)
    print(f"{Colors.FAIL}[!] Tor did not start within 60 seconds. Check: sudo service tor status{Colors.ENDC}")
    sys.exit(1)


def _restart_tor_fresh():
    """Tor service restart karke fresh circuits lo. Auto-renew me use hota hai."""
    print(f"{Colors.OKCYAN}[*] Restarting Tor for fresh circuits...{Colors.ENDC}")
    sys.stdout.flush()
    subprocess.run(["sudo", "service", "tor", "restart"], capture_output=True)
    for _ in range(30):
        try:
            s = socket.create_connection(("127.0.0.1", 9050), timeout=2)
            s.close()
            print(f"{Colors.OKGREEN}[+] Tor is back with fresh circuits.{Colors.ENDC}")
            return True
        except OSError:
            time.sleep(2)
    print(f"{Colors.WARNING}[!] Tor 60s me wapas nahi aaya — worker phir bhi restart hoga.{Colors.ENDC}")
    return False


def _kill_own_chrome():
    """Is worker ke bache-khuche (zombie) browser processes maaro. Sibling workers ko haath nahi."""
    me = os.getpid()
    killed = 0
    try:
        for pid in os.listdir("/proc"):
            if not pid.isdigit():
                continue
            try:
                with open(f"/proc/{pid}/stat") as f:
                    parts = f.read().rsplit(")", 1)
                    ppid = int(parts[1].split()[1])
                with open(f"/proc/{pid}/comm") as f:
                    comm = f.read().strip().lower()
            except Exception:
                continue
            if ppid == me and "chrome" in comm:
                try:
                    os.kill(int(pid), 9)
                    killed += 1
                except Exception:
                    pass
    except Exception:
        pass
    if killed:
        print(f"[*] Cleaned {killed} leftover browser process(es).")
    return killed


def install_python_deps():
    """
    Auto-install required Python packages if missing.
    """
    required = [
        "playwright", "playwright-stealth", "pyotp", "requests"
    ]
    for pkg in required:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            print(f"{Colors.OKCYAN}[*] Installing missing package: {pkg}{Colors.ENDC}")
            subprocess.run([sys.executable, "-m", "pip", "install", pkg], check=True)
    
    # Install Playwright browsers (chromium)
    result = subprocess.run(
        [sys.executable, "-m", "playwright", "install", "chromium"],
        capture_output=True, text=True
    )
    if "already installed" not in result.stdout + result.stderr:
        subprocess.run([sys.executable, "-m", "playwright", "install-deps", "chromium"],
                       capture_output=True)
    print(f"{Colors.OKGREEN}[+] All Python dependencies ready.{Colors.ENDC}")


async def main():
    # Suppress harmless asyncio cleanup warnings on Linux
    loop = asyncio.get_event_loop()
    def _quiet_exception_handler(loop, context):
        msg = str(context.get("exception", context.get("message", "")))
        # Suppress proxy task cleanup noise
        if any(x in msg for x in [
            "Task was destroyed", "ConnectionReset", "BrokenPipe",
            "ConnectionAborted", "handle_client"
        ]):
            return
        loop.default_exception_handler(context)
    loop.set_exception_handler(_quiet_exception_handler)

    async with async_playwright() as playwright:
        await run(playwright)


if __name__ == "__main__":
    print(f"{Colors.HEADER}{Colors.BOLD}=== {WORKER_ID} | Fleet Mode | {WORKER_THREADS} threads ==={Colors.ENDC}")
    install_python_deps()
    setup_tor()
    start_imap_listener()
    import threading as _th
    _th.Thread(target=heartbeat_loop, daemon=True).start()
    _th.Thread(target=command_loop, daemon=True).start()
    asyncio.run(main())
